# Generated by Django 3.1.7 on 2021-03-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='on_sidebar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='on_sidebar_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterIndexTogether(
            name='category',
            index_together={('on_sidebar', 'on_sidebar_order')},
        ),
    ]
