# Generated by Django 3.1.7 on 2021-03-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210329_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='on_sidebar',
            field=models.BooleanField(default=False, verbose_name='Bosh sahifada chiqsinmi?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Faol'), (0, 'Nofaol')], default=1),
        ),
    ]
